### ISSUE TITLE
Add CG PyPi maintainer!

### ISSUE THREAD

**Issue by dnil** [moonso/query_phenomizer#7]
Hi again, 

this one is actually for you Måns: would be great if you could add me `dNil` and `clingen` as PyPi maintainers for the repo so we can publish the latest "fix". Thank you kindly!

https://pypi.org/project/query_phenomizer/

**Comment by moonso** [comment]
Hi @dnil ! 
Added you as owner and clingen as maintainer. 

Good luck 🍀

**Comment by dnil** [comment]
Tackar, tackar! 🙏🏻
